# Generated by Django 4.2.15 on 2024-11-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
